apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "LoginNextJS"
  description: "An example screen created with NextJS and Styled Components"
  links:
    - title: Website
      url: https://www.globo.com/
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: ValberJunior/LoginNextJS
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: nextjs.yml,nextjs.yml
    website/url: https://www.globo.com/
    kong-manager/service-name: 7c62281d-2ca4-428d-884f-a9d95b98438d
    kong-manager/instance: /kong-manager/api
   
spec:
  type: website
  lifecycle: prod
  owner: "devops"
  url: https://www.globo.com/
#  subcomponentOf: 'cluster:default/devportal-kubernetes'
#  dependsOn: ["environment:default/Enviroment_Ecs"]
