apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "LoginNextJS"
  description: "An example screen created with NextJS and Styled Components"
  environment:
    cluster_instructions: |
      mkdir test
      aws eks get kubeconfig
  links:
    - title: Website
      url: https://www.globo.com/
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
#    - title: Spec
#      url: 'api:default/spec-1303'
  annotations:
    github.com/project-slug: ValberJunior/LoginNextJS
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: start.yml,stop.yml,update.yml,remove.yml
    website/url: https://www.globo.com/
    kong-manager/service-name: vkpr.devportal-petclinic.80
    kong-manager/instance: /kong-manager/api
    cluster/instructions: |
        mkdir test
        aws eks get kubeconfig
   
spec:
  type: website
  lifecycle: prod
  owner: "devops"
  url: https://www.globo.com/
#  definition:
#   $text: 'api:default/spec-1303'
  providesApis:
    - api-demo
  #subcomponentOf: 'environment:default/ec2_environment'
  system: 'environment:default/ec2_environment'
