name: Update DNS

on:
  workflow_dispatch:
    inputs:
        name:
          type: choice
          description: Who to greet
          options: 
          - monalisa
          - cschleiden
        message:
          required: true
        use-emoji:
          type: boolean
          description: Include 🎉🤣 emojis
        environment:
          type: environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Detect package manager
        run: |
          echo "Detect package manager"
      - name: Write Message
        run: |
          echo "Hello World"
      - name: Publish
        run: |
          echo "Deploy Site..."
      - name: Finish
        run: |
          echo "The end *-*"

