name: Deploy NextJS

on:
  workflow_dispatch:

jobs:
  delay:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 2 minutes
        run: sleep 120  # 120 seconds = 2 minutes

  build:
    needs: delay
    runs-on: ubuntu-latest
    steps:
      - name: Detect package manager
        run: |
          echo "Detect package manager"
      - name: Write Message
        run: |
          echo "Hello World"
      - name: Publish
        run: |
          echo "Deploy Site..."
      - name: Finish
        run: |
          echo "The end *-*"
