name: Deploy NextJS

on:
  workflow_dispatch:
   inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
        default: 'monalisa'
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
        default: true
        required: false
      number:
        type: number
        description: The number
        required: false
        default: '3548'
      text:
        type: string
        description: String for test
        required: true
        default: 'login teste'

jobs:
  delay:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 2 minutes
        run: sleep 120  # 120 seconds = 2 minutes

  build:
    needs: delay
    runs-on: ubuntu-latest
    steps:
      - name: Detect package manager
        run: |
          echo "Detect package manager"
      - name: Write Message
        run: |
          echo "Hello World"
      - name: Publish
        run: |
          echo "Deploy Site..."
      - name: Finish
        run: |
          echo "The end *-*"
